version: "3"

services:
  api:
    build: .
    container_name: toast-api
    restart: on-failure
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - .:/app

  db:
    image: postgres:11.7-alpine
    container_name: toast-db
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
