version: "3.5"

services:
  api:
    build: .
    container_name: toast-api
    restart: on-failure
    env_file:
      - .env
    ports:
      - 8080:8080

  # Lint container since WSL won't map volumes in docker
  linter:
    image: golangci/golangci-lint:v1.24.0
    working_dir: /app
    command: golangci-lint run -v
    volumes:
      - .:/app
