version: "3.5"

services:
  api:
    build:
      context: .
      target: development
    container_name: toast-api
    restart: on-failure
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - .:/app
